### ISSUE TITLE
[REQ] SOCKS5 proxy on the client side

### ISSUE THREAD

**Issue by gzm55** [payfazz/stdiotunnel#1]
can we setup a socks proxy on the client side, just like `ssh -D port` do, then we do not need the start up the client process for each connection.

**Comment by win-t** [comment]
IHMO, socks5 proxy is not in the scope of stdiotunnel project
but, you can run separate socks server, and make stdiotunnel client connect to it,
for example
```
[program with socks5 client] --\
                                --> [stdiotunnel server] --> [stdiotunnel client] --> [socks5 server]
[program with socks5 client] --/
```
